/**
 * Parse the --command-only output from the wordpress-sync CLI
 * into structured command entries grouped by section.
 */

export interface CommandEntry {
  section: string;
  description: string;
  command: string;
  environment: 'local' | 'remote' | 'both';
  user?: string;
}

/**
 * Parse the --command-only output format.
 *
 * Expected format:
 *   === Section Name ===
 *   LOCAL COMMANDS:
 *   # Description of what this does
 *   [user] command --flags
 *
 *   REMOTE COMMANDS:
 *   # Another description
 *   command --other-flags
 */
export function parseCommandOutput(output: string): CommandEntry[] {
  const entries: CommandEntry[] = [];
  const lines = output.split('\n');

  let currentSection = 'General';
  let currentEnvironment: 'local' | 'remote' | 'both' = 'local';
  let currentDescription = '';

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) continue;

    // Check for section headers: === Section Name ===
    const sectionMatch = trimmed.match(/^={2,}\s*(.+?)\s*={2,}$/);
    if (sectionMatch) {
      currentSection = sectionMatch[1].trim();
      continue;
    }

    // Check for environment markers
    if (/^LOCAL\s+COMMANDS?\s*:?$/i.test(trimmed)) {
      currentEnvironment = 'local';
      continue;
    }
    if (/^REMOTE\s+COMMANDS?\s*:?$/i.test(trimmed)) {
      currentEnvironment = 'remote';
      continue;
    }
    if (/^(LOCAL\s*[&+]\s*REMOTE|BOTH)\s+COMMANDS?\s*:?$/i.test(trimmed)) {
      currentEnvironment = 'both';
      continue;
    }

    // Check for description comments: # Description
    if (trimmed.startsWith('#')) {
      currentDescription = trimmed.replace(/^#\s*/, '');
      continue;
    }

    // Check for separator/decoration lines
    if (/^[-=_]{3,}$/.test(trimmed)) {
      continue;
    }

    // Everything else is a command line (indented or not)
    const command = trimmed;

    // Check for user context: [user] command
    let user: string | undefined;
    const userMatch = command.match(/^\[([^\]]+)\]\s+(.+)$/);
    let actualCommand = command;
    if (userMatch) {
      user = userMatch[1];
      actualCommand = userMatch[2];
    }

    entries.push({
      section: currentSection,
      description: currentDescription || '',
      command: actualCommand,
      environment: currentEnvironment,
      user,
    });

    // Reset description after consuming it
    currentDescription = '';
  }

  return entries;
}

/**
 * Group command entries by section name.
 */
export function groupBySection(entries: CommandEntry[]): Map<string, CommandEntry[]> {
  const groups = new Map<string, CommandEntry[]>();
  for (const entry of entries) {
    const existing = groups.get(entry.section);
    if (existing) {
      existing.push(entry);
    } else {
      groups.set(entry.section, [entry]);
    }
  }
  return groups;
}

/**
 * Export command entries as a shell script with section comments.
 */
export function exportAsShellScript(entries: CommandEntry[]): string {
  const lines: string[] = ['#!/bin/bash', '# Generated by WordPress Sync GUI', ''];

  const groups = groupBySection(entries);
  for (const [section, sectionEntries] of groups) {
    lines.push(`# ${'='.repeat(50)}`);
    lines.push(`# ${section}`);
    lines.push(`# ${'='.repeat(50)}`);
    lines.push('');

    for (const entry of sectionEntries) {
      if (entry.description) {
        lines.push(`# ${entry.description}`);
      }
      if (entry.user) {
        lines.push(`# Run as: ${entry.user}`);
      }
      if (entry.environment === 'remote') {
        lines.push(`# Environment: REMOTE`);
      }
      lines.push(entry.command);
      lines.push('');
    }
  }

  return lines.join('\n');
}
